import ModalDistribution.Core.History
import ModalDistribution.Core.Semifilter

open Set
open History
open scoped Semifilter

/-!
# Model structures

This file sets up the model structures from Section 3.2 of the HBB paper.
We package the signature components, introduce the generated event and
atomic predicate types, and formalise models together with their local
view operations (Definition 3.2.3 and Definition 3.2.7).

## Main definitions

* `Signature`: the tuple of symbols and values from Definition 3.1.1.
* `Signature.Event`: generated events `E(v₁, …, vₙ)` (Definition 3.1.1(2)).
* `Signature.AtomicPred`: generated atomic predicates `P(v₁, …, vₙ)`
  (Definition 3.1.1(2)).
* `Model`: the tuple `(P, H, ϱ, ς)` from Definition 3.2.3.
* `Model.LocalHistory`: transitive subsets used for local views
  (Definition 3.2.7).

-/

namespace ModalDistribution

universe u₁ u₂ u₃ u₄ u₅

/-- Definition 3.1.1: a logical signature packages the symbols and values. -/
structure Signature where
  /-- Event symbols (Definition 3.1.1(1)). -/
  EventSymb : Type u₁
  /-- Predicate symbols (Definition 3.1.1(1)). -/
  PredSymb : Type u₂
  /-- Values (Definition 3.1.1(1)); also used for learners (Remark 3.2.10). -/
  Value : Type u₃

namespace Signature

/-- Definition 3.1.1(2): events generated by the signature symbols. -/
structure Event (S : Signature) where
  /-- The event symbol `E`. -/
  sym : S.EventSymb
  /-- Arguments `v₁, …, vₙ` carried by the event. -/
  args : List S.Value

/-- Definition 3.1.1(2): atomic predicates generated by the signature symbols. -/
structure AtomicPred (S : Signature) where
  /-- The predicate symbol `P`. -/
  sym : S.PredSymb
  /-- Arguments `v₁, …, vₙ` carried by the predicate. -/
  args : List S.Value

/-- Events as a type (notation `Event(Σ)` in the paper). -/
abbrev EventType (S : Signature) : Type _ := Event S

/-- Atomic predicates as a type (notation `AtomicPred(Σ)` in the paper). -/
abbrev AtomicPredType (S : Signature) : Type _ := AtomicPred S

end Signature

/-- Definition 3.2.3: models combine histories and interpretations. -/
structure Model (S : Signature) (P : Type u₅) [Nonempty P] where
  /-- History structure `H` (Definition 3.2.3(2)). -/
  history : History P (Signature.EventType S)
  /-- Predicate interpretation `ϱ` (Definition 3.2.3(3)). -/
  predInterp :
    (p : P) →
      PreHistory P (Signature.EventType S) →
      Set (Signature.AtomicPredType S)
  /-- Learner interpretation `ς` (Definition 3.2.3(4)). -/
  learner : Signature.Value S → Semifilter P

namespace Model

variable {S : Signature} {P : Type u₅} [Nonempty P]
variable (M : Model S P)

/-- Every learner interpretation is nonempty (Definition 3.2.3(4)). -/
theorem learner_nonempty (v : Signature.Value S) :
    ∃ O : Set P, O ∈ (M.learner v).quorums := by
  simpa using (M.learner v).nonempty

/-- Learner interpretations are up-closed under supersets. -/
theorem learner_upwardClosed (v : Signature.Value S) :
    ∀ {O O' : Set P},
      O ∈ (M.learner v).quorums →
      O ⊆ O' →
      O' ∈ (M.learner v).quorums := by
  intro O O' hO hsubset
  exact (M.learner v).upwardClosed hO hsubset

/-- Learner interpretations contain pairwise-intersecting quorums. -/
theorem learner_pairwiseInter (v : Signature.Value S) :
    ∀ {O O' : Set P},
      O ∈ (M.learner v).quorums →
      O' ∈ (M.learner v).quorums →
      O ≬ O' := by
  intro O O' hO hO'
  exact (M.learner v).pairwiseInter hO hO'

end Model

end ModalDistribution
