import ModalDistribution.Core.History
import ModalDistribution.Core.Semifilter

open Set
open History
open scoped Semifilter

/-!
# Model structures

This file sets up the model structures for HBB.
We package the signature components, introduce the generated event and
atomic predicate types, and formalise models together with their local
view operations.

## Main definitions

* `Signature`: the tuple of symbols and values.
* `Signature.Event`: generated events `E(v₁, …, vₙ)`.
* `Signature.AtomicPred`: generated atomic predicates `P(v₁, …, vₙ)`.
* `Model`: the tuple `(P, H, ϱ, ς)`.

-/

namespace ModalDistribution

universe u₁ u₂ u₃ u₄ u₅

/-- Paper: Definition 3.1.1(1); values double as learners per Remark 3.3.8. A logical signature packages the symbols and values. -/
structure Signature where
  /-- Event symbols. -/
  EventSymb : Type u₁
  /-- Predicate symbols. -/
  PredSymb : Type u₂
  /-- Values; also used for learners. -/
  Value : Type u₃

namespace Signature

/-- Paper: Definition 3.1.1(2) (events over Σ). Events generated by the signature symbols. -/
structure Event (S : Signature) where
  /-- The event symbol `E`. -/
  sym : S.EventSymb
  /-- Arguments `v₁, …, vₙ` carried by the event. -/
  args : List S.Value

/-- Paper: Definition 3.1.1(2) (atomic predicates over Σ). Atomic predicates generated by the signature symbols. -/
structure AtomicPred (S : Signature) where
  /-- The predicate symbol `P`. -/
  sym : S.PredSymb
  /-- Arguments `v₁, …, vₙ` carried by the predicate. -/
  args : List S.Value

/-- Events as a type. -/
abbrev EventType (S : Signature) : Type _ := Event S

/-- Atomic predicates as a type. -/
abbrev AtomicPredType (S : Signature) : Type _ := AtomicPred S

end Signature

/-- Paper: Definition 3.3.3 (models). Models combine histories and interpretations. -/
structure Model (S : Signature) (P : Type u₅) [Nonempty P] where
  /-- History structure `H`. -/
  history : History P (Signature.EventType S)
  /-- Predicate interpretation `ϱ`. -/
  predInterp :
    (p : P) →
      PreHistory P (Signature.EventType S) →
      Set (Signature.AtomicPredType S)
  /-- Learner interpretation `ς`. -/
  learner : Signature.Value S → Semifilter P

namespace Model

variable {S : Signature} {P : Type u₅} [Nonempty P]
variable (M : Model S P)

end Model
end ModalDistribution
