import ModalDistribution.Core.History
import ModalDistribution.Core.Semifilter

open Set
open scoped Semifilter

/-!
# Model structures

This file sets up the model structures from Section 3.2 of the HBB paper.
We package the signature components, introduce the generated event and
atomic predicate types, and formalise models together with their local
view operations (Definition 3.2.3 and Definition 3.2.7).

## Main definitions

* `Signature`: the tuple of symbols and values from Definition 3.1.1.
* `Signature.Event`: generated events `E(v₁, …, vₙ)` (Definition 3.1.1(2)).
* `Signature.AtomicPred`: generated atomic predicates `P(v₁, …, vₙ)`
  (Definition 3.1.1(2)).
* `Model`: the tuple `(P, H, ϱ, ς)` from Definition 3.2.3.
* `Model.LocalHistory`: transitive subsets used for local views
  (Definition 3.2.7).
* `Model.localView`: restriction of a model to a local view
  (Definition 3.2.7).

-/

namespace ModalDistribution

universe u₁ u₂ u₃ u₄ u₅

/-- Definition 3.1.1: a logical signature packages the symbols and values. -/
structure Signature where
  /-- Variable symbols (Definition 3.1.1(1)). -/
  VarSymb : Type u₁
  /-- Event symbols (Definition 3.1.1(1)). -/
  EventSymb : Type u₂
  /-- Predicate symbols (Definition 3.1.1(1)). -/
  PredSymb : Type u₃
  /-- Values (Definition 3.1.1(1)); also used for learners (Remark 3.2.10). -/
  Value : Type u₄

namespace Signature

/-- Definition 3.1.1(2): events generated by the signature symbols. -/
structure Event (S : Signature) where
  /-- The event symbol `E`. -/
  sym : S.EventSymb
  /-- Arguments `v₁, …, vₙ` carried by the event. -/
  args : List S.Value

/-- Definition 3.1.1(2): atomic predicates generated by the signature symbols. -/
structure AtomicPred (S : Signature) where
  /-- The predicate symbol `P`. -/
  sym : S.PredSymb
  /-- Arguments `v₁, …, vₙ` carried by the predicate. -/
  args : List S.Value

/-- Events as a type (notation `Event(Σ)` in the paper). -/
abbrev EventType (S : Signature) : Type _ := Event S

/-- Atomic predicates as a type (notation `AtomicPred(Σ)` in the paper). -/
abbrev AtomicPredType (S : Signature) : Type _ := AtomicPred S

end Signature

/-- Definition 3.2.3: models combine histories and interpretations. -/
structure Model (S : Signature) (P : Type u₅) [Nonempty P] where
  /-- History structure `H` (Definition 3.2.3(2)). -/
  history : History P (Signature.EventType S)
  /-- Predicate interpretation `ϱ` (Definition 3.2.3(3)). -/
  predInterp :
    (p : P) →
      PreHistory P (Signature.EventType S) →
      Set (Signature.AtomicPredType S)
  /-- Learner interpretation `ς` (Definition 3.2.3(4)). -/
  learner : Signature.Value S → Semifilter P

namespace Model

variable {S : Signature} {P : Type u₅} [Nonempty P]
variable (M : Model S P)

/-- Definition 3.2.7: restrict a model to a transitive subhistory. -/
def localView
    (H : History P (Signature.EventType S)) : Model S P :=
  { history := H
    predInterp :=  M.predInterp
    learner := M.learner }

infixl:70 " ∣ᵥ " => localView

@[simp] lemma localView_history_val
    (H : History P (Signature.EventType S)) :
    (M.localView H).history.val = H := by
  rfl

/-- Predicate interpretation in a local view reuses the ambient interpretation. -/
@[simp] lemma localView_predInterp
    (H : History P (Signature.EventType S)) (p : P)
    (K : PreHistory P (Signature.EventType S)) :
    (M.localView H).predInterp p K =
      M.predInterp p K := by
  rfl

/-- Learner interpretations remain unchanged under restriction. -/
@[simp] lemma localView_learner
    (H : History P (Signature.EventType S)) (v : Signature.Value S) :
    (M.localView H).learner v = M.learner v := by
  rfl

@[simp] lemma history_subset :
    M.history ⊆trn M.history.val :=
  transitiveSubset_refl M.history

/-- Restricting along the whole history yields the same model (Lemma 3.2.8(1)). -/
@[simp] lemma localView_full :
    M.localView M.history = M := by
  cases M
  rfl

/-- Composite restrictions collapse to a single inclusion (Lemma 3.2.8(2)). -/
lemma localView_comp
    (H : History P (Signature.EventType S))
    (H' : History P (Signature.EventType S)) :
    (M.localView H).localView H' =
      M.localView H' := by
  cases M
  rfl

/-- Idempotence of restriction (Lemma 3.2.8(3)). -/
@[simp] lemma localView_idem
    (H : History P (Signature.EventType S)) :
    (M.localView H).localView H = M.localView H := by
  cases M
  rfl

/-- Every learner interpretation is nonempty (Definition 3.2.3(4)). -/
theorem learner_nonempty (v : Signature.Value S) :
    ∃ O : Set P, O ∈ (M.learner v).quorums := by
  simpa using (M.learner v).nonempty

/-- Learner interpretations are up-closed under supersets. -/
theorem learner_upwardClosed (v : Signature.Value S) :
    ∀ {O O' : Set P},
      O ∈ (M.learner v).quorums →
      O ⊆ O' →
      O' ∈ (M.learner v).quorums := by
  intro O O' hO hsubset
  exact (M.learner v).upwardClosed hO hsubset

/-- Learner interpretations contain pairwise-intersecting quorums. -/
theorem learner_pairwiseInter (v : Signature.Value S) :
    ∀ {O O' : Set P},
      O ∈ (M.learner v).quorums →
      O' ∈ (M.learner v).quorums →
      O ≬ O' := by
  intro O O' hO hO'
  exact (M.learner v).pairwiseInter hO hO'

end Model

end ModalDistribution
